version: '2.1'
services:
  postgres:
    image: postgres:9.6-alpine
    expose:
    - "5432"

  postgresql-connector:
    image: sysunite/weaver-database-postgresql:4.14.0-alpha.0-transactions
    expose:
    - "4567"
    environment:
    - POSTGRES_HOST=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASS=root
    ports:
    - "4567:4567"

  file-system:
    image: minio/minio:RELEASE.2018-12-27T18-33-08Z
    expose:
    - "9000"
    environment:
    - MINIO_ACCESS_KEY=NYLEXGR6MF2IE99LZ4UE
    - MINIO_SECRET_KEY=CjMuTRwYPcneXnGac2aQH0J+EdYdehTW4Cw7bZGD
    command: server /data
    ports:
    - "9000:9000"

  weaver-server:
    image: sysunite/weaver-server:3.17.0-alpha.0-transactions
    expose:
    - "9487"
    ports:
    - "9487:9487"
    volumes:
    - "./weaver-server-config/local.coffee:/usr/src/app/config/local.coffee"
    - "./weaver-server-models:/usr/src/app/models"
