version: '2.1'
services:
  postgres:
    image: postgres:9.6-alpine
    expose:
    - "5432"

  postgresql-connector:
    image: sysunite/weaver-database-postgresql:0.0.25
    links:
    - postgres
    expose:
    - "4567"
    environment:
    - POSTGRES_HOST=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASS=root

  file-system:
    image: minio/minio:RELEASE.2017-04-25T01-27-49Z
    expose:
    - "9000"
    environment:
    - MINIO_ACCESS_KEY=NYLEXGR6MF2IE99LZ4UE
    - MINIO_SECRET_KEY=CjMuTRwYPcneXnGac2aQH0J+EdYdehTW4Cw7bZGD
    command: server /data

  weaver-server:
    image: sysunite/weaver-server:3.0.10-beta.1
    expose:
    - "9487"
    ports:
    - "9487:9487"
    links:
    - postgresql-connector
    - file-system
    volumes:
    - "./weaver-server-config:/usr/src/app/config"
